// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopster.Shopster.DAL.AppDbContext;

#nullable disable

namespace Shopster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230418131413_CommodityTest")]
    partial class CommodityTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopster.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9106fe7b-0386-4269-b3d1-7ff1c5c730b3"),
                            Name = "ctg1"
                        },
                        new
                        {
                            Id = new Guid("d1aa8d00-16af-4881-a036-5aafdb687c7b"),
                            Name = "ctg22"
                        },
                        new
                        {
                            Id = new Guid("b5df0ce7-b292-4121-bce7-871edfaa6b13"),
                            Name = "ctg3"
                        },
                        new
                        {
                            Id = new Guid("0d304865-047b-4f98-b47b-c6a9aa8d8f0e"),
                            Name = "ctg5"
                        },
                        new
                        {
                            Id = new Guid("3fb6a786-495b-4aba-bb9d-467847ca42d2"),
                            Name = "ctg6"
                        });
                });

            modelBuilder.Entity("Shopster.Entities.CommodityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Commodity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("190394f2-1be2-44c7-b695-a60c7c02c400"),
                            CategoryId = new Guid("9106fe7b-0386-4269-b3d1-7ff1c5c730b3"),
                            Description = "desc1",
                            ManufacturerId = new Guid("c997e832-179a-4d3e-a300-26482ede98b8"),
                            Name = "ctg1",
                            Picture = "picture.jpg",
                            Price = 10m,
                            Quantity = 2,
                            Weight = 15f
                        });
                });

            modelBuilder.Entity("Shopster.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04007188-becf-4518-8d39-7ff1a3ba53ef"),
                            CountryOfOrigin = "CZ",
                            Description = "desc1",
                            Logo = "logo1.png",
                            Name = "manu1"
                        },
                        new
                        {
                            Id = new Guid("c997e832-179a-4d3e-a300-26482ede98b8"),
                            CountryOfOrigin = "CZ",
                            Description = "desc2",
                            Logo = "logo2.png",
                            Name = "manu2"
                        },
                        new
                        {
                            Id = new Guid("ba797672-2462-4679-8852-ac56b5150800"),
                            CountryOfOrigin = "CZ",
                            Description = "desc3",
                            Logo = "logo3.png",
                            Name = "manu3"
                        },
                        new
                        {
                            Id = new Guid("0b18e709-ad57-4c89-8dda-3e40b928466b"),
                            CountryOfOrigin = "CZ",
                            Description = "desc4",
                            Logo = "logo4.png",
                            Name = "manu4"
                        });
                });

            modelBuilder.Entity("Shopster.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommodityEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityEntityId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("Shopster.Entities.CommodityEntity", b =>
                {
                    b.HasOne("Shopster.Entities.CategoryEntity", "Category")
                        .WithMany("Commodities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopster.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("Commodities")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Shopster.Entities.RatingEntity", b =>
                {
                    b.HasOne("Shopster.Entities.CommodityEntity", "Commodity")
                        .WithMany("Ratings")
                        .HasForeignKey("CommodityEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("Shopster.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Commodities");
                });

            modelBuilder.Entity("Shopster.Entities.CommodityEntity", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Shopster.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
