// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopster.Shopster.DAL.AppDbContext;

#nullable disable

namespace Shopster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230418132812_RatingsTest")]
    partial class RatingsTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopster.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1013de7d-c130-4440-ac15-e0e224f9aefc"),
                            Name = "ctg1"
                        },
                        new
                        {
                            Id = new Guid("5cf1cc47-04ac-48f8-b43c-5bc96a40ac8e"),
                            Name = "ctg3"
                        },
                        new
                        {
                            Id = new Guid("7b961675-8b26-4866-af16-7a3eaffd7949"),
                            Name = "ctg5"
                        },
                        new
                        {
                            Id = new Guid("09efdfd4-4e51-4c66-bf72-b80cc71de970"),
                            Name = "ctg6"
                        });
                });

            modelBuilder.Entity("Shopster.Entities.CommodityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Commodity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c9cb969-ad41-4be3-a7ca-a65ac3371508"),
                            CategoryId = new Guid("1013de7d-c130-4440-ac15-e0e224f9aefc"),
                            Description = "desc1",
                            ManufacturerId = new Guid("334a87ef-d557-49cc-9c65-d6db05dd7425"),
                            Name = "cmd1",
                            Picture = "picture.jpg",
                            Price = 10m,
                            Quantity = 2,
                            Weight = 20f
                        },
                        new
                        {
                            Id = new Guid("6d46d6d6-7620-4912-9a19-57bf1a672aa9"),
                            CategoryId = new Guid("5cf1cc47-04ac-48f8-b43c-5bc96a40ac8e"),
                            Description = "desc2",
                            ManufacturerId = new Guid("ae9d1446-b6b5-4ad5-a983-e37eac15370f"),
                            Name = "cmd2",
                            Picture = "picture.jpg",
                            Price = 1m,
                            Quantity = 2,
                            Weight = 5f
                        },
                        new
                        {
                            Id = new Guid("b65682de-f311-44d4-bd55-e2ea99cc5fbc"),
                            CategoryId = new Guid("09efdfd4-4e51-4c66-bf72-b80cc71de970"),
                            Description = "desc3",
                            ManufacturerId = new Guid("334a87ef-d557-49cc-9c65-d6db05dd7425"),
                            Name = "cmd3",
                            Picture = "picture.jpg",
                            Price = 23254m,
                            Quantity = 20,
                            Weight = 15f
                        },
                        new
                        {
                            Id = new Guid("fff73b1a-34f5-4539-a004-d2cdd5a55994"),
                            CategoryId = new Guid("09efdfd4-4e51-4c66-bf72-b80cc71de970"),
                            Description = "desc4",
                            ManufacturerId = new Guid("94cd9937-55d7-4dac-8ec5-235efbd905dd"),
                            Name = "cmd4",
                            Picture = "picture.jpg",
                            Price = 55m,
                            Quantity = 10,
                            Weight = 15f
                        });
                });

            modelBuilder.Entity("Shopster.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("759a91d0-afc6-422d-a388-c8b517935667"),
                            CountryOfOrigin = "CZ",
                            Description = "desc1",
                            Logo = "logo1.png",
                            Name = "manu1"
                        },
                        new
                        {
                            Id = new Guid("ae9d1446-b6b5-4ad5-a983-e37eac15370f"),
                            CountryOfOrigin = "CZ",
                            Description = "desc2",
                            Logo = "logo2.png",
                            Name = "manu2"
                        },
                        new
                        {
                            Id = new Guid("334a87ef-d557-49cc-9c65-d6db05dd7425"),
                            CountryOfOrigin = "CZ",
                            Description = "desc3",
                            Logo = "logo3.png",
                            Name = "manu3"
                        },
                        new
                        {
                            Id = new Guid("94cd9937-55d7-4dac-8ec5-235efbd905dd"),
                            CountryOfOrigin = "CZ",
                            Description = "desc4",
                            Logo = "logo4.png",
                            Name = "manu4"
                        });
                });

            modelBuilder.Entity("Shopster.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommodityEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityEntityId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9056e54a-180c-4c13-a637-8245d5f368fd"),
                            CommodityEntityId = new Guid("6d46d6d6-7620-4912-9a19-57bf1a672aa9"),
                            Description = "desc1",
                            Stars = 1,
                            Title = "title1"
                        },
                        new
                        {
                            Id = new Guid("a4b57112-adeb-4645-9d19-d65b5218fbc2"),
                            CommodityEntityId = new Guid("6d46d6d6-7620-4912-9a19-57bf1a672aa9"),
                            Description = "desc2",
                            Stars = 5,
                            Title = "title2"
                        },
                        new
                        {
                            Id = new Guid("2ad975f5-a92c-4ba6-b26c-23e141de1774"),
                            CommodityEntityId = new Guid("fff73b1a-34f5-4539-a004-d2cdd5a55994"),
                            Description = "desc3",
                            Stars = 5,
                            Title = "title3"
                        },
                        new
                        {
                            Id = new Guid("53da0d9c-569e-4ad1-a2b7-7570886ea1ca"),
                            CommodityEntityId = new Guid("0c9cb969-ad41-4be3-a7ca-a65ac3371508"),
                            Description = "desc4",
                            Stars = 4,
                            Title = "title4"
                        });
                });

            modelBuilder.Entity("Shopster.Entities.CommodityEntity", b =>
                {
                    b.HasOne("Shopster.Entities.CategoryEntity", "Category")
                        .WithMany("Commodities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopster.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("Commodities")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Shopster.Entities.RatingEntity", b =>
                {
                    b.HasOne("Shopster.Entities.CommodityEntity", "Commodity")
                        .WithMany("Ratings")
                        .HasForeignKey("CommodityEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("Shopster.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Commodities");
                });

            modelBuilder.Entity("Shopster.Entities.CommodityEntity", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Shopster.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
