// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopster.DAL;

#nullable disable

namespace Shopster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopster.DAL.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6ca87d1-ad83-a11b-3725-205c718a331d"),
                            Name = "Beauty & Industrial"
                        },
                        new
                        {
                            Id = new Guid("66259208-4099-1b19-44f3-00fe98396ef0"),
                            Name = "Industrial & Games"
                        },
                        new
                        {
                            Id = new Guid("f535824d-88df-32d0-26a3-7af1f61f848c"),
                            Name = "Home, Industrial & Music"
                        },
                        new
                        {
                            Id = new Guid("f6e8dfdd-11a8-38ec-bdf7-962164980a72"),
                            Name = "Shoes, Clothing & Music"
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CommodityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Commodity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2067f69-9181-4edb-8b36-4346c7906a6a"),
                            CategoryId = new Guid("f535824d-88df-32d0-26a3-7af1f61f848c"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ManufacturerId = new Guid("f2a27d99-8874-f369-0f29-0a73a0e38d2e"),
                            Name = "Licensed Steel Salad",
                            Picture = "https://picsum.photos/640/480/?image=53",
                            Price = 69.1803058136518801m,
                            Quantity = 21,
                            Weight = 31.15961f
                        },
                        new
                        {
                            Id = new Guid("6659f0ce-e1da-2152-be17-04840fb37d46"),
                            CategoryId = new Guid("66259208-4099-1b19-44f3-00fe98396ef0"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ManufacturerId = new Guid("b7afcea0-dc5b-bfa6-e585-b468e58410b1"),
                            Name = "Generic Plastic Gloves",
                            Picture = "https://picsum.photos/640/480/?image=968",
                            Price = 187.411800010754836m,
                            Quantity = 56,
                            Weight = 9.5668955f
                        },
                        new
                        {
                            Id = new Guid("c43d6fc5-c41b-56c1-5735-97515debc14a"),
                            CategoryId = new Guid("66259208-4099-1b19-44f3-00fe98396ef0"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ManufacturerId = new Guid("b7afcea0-dc5b-bfa6-e585-b468e58410b1"),
                            Name = "Gorgeous Cotton Ball",
                            Picture = "https://picsum.photos/640/480/?image=635",
                            Price = 737.466697071283744m,
                            Quantity = 5,
                            Weight = 95.58386f
                        },
                        new
                        {
                            Id = new Guid("43943901-7b1b-935d-d3f6-19ead6e22423"),
                            CategoryId = new Guid("66259208-4099-1b19-44f3-00fe98396ef0"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ManufacturerId = new Guid("b7afcea0-dc5b-bfa6-e585-b468e58410b1"),
                            Name = "Small Metal Gloves",
                            Picture = "https://picsum.photos/640/480/?image=271",
                            Price = 154.72695226683007m,
                            Quantity = 60,
                            Weight = 17.495409f
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7afcea0-dc5b-bfa6-e585-b468e58410b1"),
                            CountryOfOrigin = "Saint Barthelemy",
                            Description = "Odit rerum ad illo illum qui. Enim laborum voluptate minus nihil voluptas quia facere architecto aut. Corporis perferendis culpa consectetur aut accusamus. Consequatur labore numquam reprehenderit. Excepturi vitae non vero inventore soluta corporis consectetur. Labore consectetur sit reprehenderit itaque sit aut ut eveniet.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/564.jpg",
                            Name = "Kulas - Gutkowski"
                        },
                        new
                        {
                            Id = new Guid("f2a27d99-8874-f369-0f29-0a73a0e38d2e"),
                            CountryOfOrigin = "Peru",
                            Description = "Quis voluptatum animi omnis sit ut nesciunt. Dolor officia qui nostrum veniam voluptate. Expedita vel commodi explicabo sapiente molestiae. Ipsum ut temporibus. Recusandae sit maxime consequuntur dolores et facilis et.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1127.jpg",
                            Name = "Mueller, Gleichner and Gutkowski"
                        },
                        new
                        {
                            Id = new Guid("29dbf0d1-eb15-0517-30c6-f9bfe9a809f7"),
                            CountryOfOrigin = "Finland",
                            Description = "Quia expedita et aut facilis qui. Ut aperiam similique aut optio beatae necessitatibus sed suscipit. Voluptates eveniet voluptatem voluptate quisquam nam quas veniam reprehenderit. Omnis magni blanditiis libero et ipsam sed maiores aut. Natus eaque perspiciatis eum quae dolorem. Id dignissimos voluptatum dolores ea voluptatem nobis.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/981.jpg",
                            Name = "Runte - Hayes"
                        },
                        new
                        {
                            Id = new Guid("9cb0d800-7504-f20e-719e-416d644847db"),
                            CountryOfOrigin = "Russian Federation",
                            Description = "Voluptatum quibusdam sapiente provident porro tenetur perferendis quis perspiciatis. Architecto eum corrupti voluptas omnis odit sed. Ipsam accusantium est distinctio nam voluptatem debitis et.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/288.jpg",
                            Name = "Lesch Group"
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CommodityEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityEntityId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            Id = new Guid("973d3853-a453-d64c-8025-eda34b8b201b"),
                            CommodityEntityId = new Guid("6659f0ce-e1da-2152-be17-04840fb37d46"),
                            Description = "Quia ut velit incidunt et. Est iure occaecati. Vero quibusdam assumenda doloribus et unde ea qui nobis.",
                            Stars = 4,
                            Title = "Laborum eius fugit asperiores ut unde est."
                        },
                        new
                        {
                            Id = new Guid("4ff3ef5a-a11e-5779-dec9-bf61a8dbc6d0"),
                            CommodityEntityId = new Guid("43943901-7b1b-935d-d3f6-19ead6e22423"),
                            Description = "Quia quo libero aut omnis. Sed aut non dolor provident autem. Cum nihil voluptatem id dolore. Est quia harum qui assumenda ab at. Incidunt id adipisci nihil reiciendis eveniet dolores qui eum.",
                            Stars = 3,
                            Title = "Velit possimus in ad pariatur ipsa et est."
                        },
                        new
                        {
                            Id = new Guid("aa1546ee-393c-4a56-2d8c-b5e4d8d2fa2f"),
                            CommodityEntityId = new Guid("43943901-7b1b-935d-d3f6-19ead6e22423"),
                            Description = "Et soluta dolores dolorum voluptatem harum ea esse cupiditate. Distinctio dicta est. Autem magni cum tempora fuga.",
                            Stars = 3,
                            Title = "Perspiciatis cumque vero itaque eos et eveniet vel dolores sunt."
                        },
                        new
                        {
                            Id = new Guid("295333c8-d328-f22b-6f88-1c4ad578f52c"),
                            CommodityEntityId = new Guid("f2067f69-9181-4edb-8b36-4346c7906a6a"),
                            Description = "Ab tempore iure exercitationem. Culpa sit consequatur aut. Asperiores dignissimos repellat ut accusamus quis quam et nobis consequatur. Animi praesentium nemo unde cupiditate harum eveniet optio. Odit quasi voluptas expedita ea sint numquam. Similique voluptatem molestiae ea et tempora dolores.",
                            Stars = 3,
                            Title = "Quos veniam esse est cum inventore."
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CommodityEntity", b =>
                {
                    b.HasOne("Shopster.DAL.Entities.CategoryEntity", "Category")
                        .WithMany("Commodities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopster.DAL.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("Commodities")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.RatingEntity", b =>
                {
                    b.HasOne("Shopster.DAL.Entities.CommodityEntity", "Commodity")
                        .WithMany("Ratings")
                        .HasForeignKey("CommodityEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Commodities");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CommodityEntity", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
