// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopster.DAL;

#nullable disable

namespace Shopster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopster.DAL.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b584c46-d100-2172-ce41-64d305ab319a"),
                            Name = "Home, Movies & Automotive"
                        },
                        new
                        {
                            Id = new Guid("363fda7d-b502-521b-fe41-ff3fba394296"),
                            Name = "Jewelery"
                        },
                        new
                        {
                            Id = new Guid("04a1c8ed-c2de-14ef-fd6d-6500dad28d31"),
                            Name = "Kids"
                        },
                        new
                        {
                            Id = new Guid("3209796e-f474-83e4-556c-723c7e2fd414"),
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CommodityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Commodity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("badfe16c-bb87-d5a3-38e5-61bb4c04a5db"),
                            CategoryId = new Guid("04a1c8ed-c2de-14ef-fd6d-6500dad28d31"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ManufacturerId = new Guid("d69b1d33-a213-0b83-7963-a4b32850a676"),
                            Name = "Intelligent Wooden Sausages",
                            Picture = "https://picsum.photos/640/480/?image=516",
                            Price = 928.343069942761954m,
                            Quantity = 82,
                            Weight = 89.21891f
                        },
                        new
                        {
                            Id = new Guid("5dfa00c1-8d8f-1d17-4d3c-cc8f77ebca97"),
                            CategoryId = new Guid("3209796e-f474-83e4-556c-723c7e2fd414"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ManufacturerId = new Guid("0f3066e1-fb28-c250-ef68-f1cb4d010bb1"),
                            Name = "Small Frozen Soap",
                            Picture = "https://picsum.photos/640/480/?image=566",
                            Price = 139.061336612376475m,
                            Quantity = 57,
                            Weight = 67.86775f
                        },
                        new
                        {
                            Id = new Guid("e68f2ad4-5879-c913-0d34-f75b37b4b71b"),
                            CategoryId = new Guid("363fda7d-b502-521b-fe41-ff3fba394296"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ManufacturerId = new Guid("d69b1d33-a213-0b83-7963-a4b32850a676"),
                            Name = "Intelligent Plastic Ball",
                            Picture = "https://picsum.photos/640/480/?image=688",
                            Price = 799.454107581933124m,
                            Quantity = 32,
                            Weight = 69.24182f
                        },
                        new
                        {
                            Id = new Guid("f1306022-13c3-8f5d-b27b-5a63d783839e"),
                            CategoryId = new Guid("3209796e-f474-83e4-556c-723c7e2fd414"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ManufacturerId = new Guid("af1db8c2-8368-98ec-4164-39539f96941a"),
                            Name = "Awesome Steel Hat",
                            Picture = "https://picsum.photos/640/480/?image=714",
                            Price = 776.32806677054851m,
                            Quantity = 73,
                            Weight = 5.5121164f
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d69b1d33-a213-0b83-7963-a4b32850a676"),
                            CountryOfOrigin = "Denmark",
                            Description = "Culpa aut id distinctio maxime est inventore voluptas. Id vel nesciunt autem. Rerum perferendis assumenda qui vero illo. Dolores omnis officiis repellat et quo autem.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/311.jpg",
                            Name = "Boehm LLC"
                        },
                        new
                        {
                            Id = new Guid("0f3066e1-fb28-c250-ef68-f1cb4d010bb1"),
                            CountryOfOrigin = "Montserrat",
                            Description = "Quae neque ipsa non. Illo ab ut quia pariatur. Odit esse nemo. Maiores consectetur nisi inventore voluptatum cupiditate minus asperiores illo. Voluptate qui cum itaque aut sint suscipit quidem at ut.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/622.jpg",
                            Name = "Cronin and Sons"
                        },
                        new
                        {
                            Id = new Guid("65b34595-c643-da79-7b21-f57f290028d0"),
                            CountryOfOrigin = "Isle of Man",
                            Description = "Eligendi ut non eos ut fugiat totam tenetur aut. Aut iste molestias et nam cum ea. Optio sit fugiat enim quam aut voluptatem. Quaerat incidunt est ipsam deserunt odio quia sit.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/10.jpg",
                            Name = "Greenholt, Effertz and Mitchell"
                        },
                        new
                        {
                            Id = new Guid("af1db8c2-8368-98ec-4164-39539f96941a"),
                            CountryOfOrigin = "Haiti",
                            Description = "Iste est voluptatem tempore mollitia necessitatibus aut. Ut qui ut illum beatae sed error et. Et tempora non sit officiis. Culpa est expedita quis nemo sit. Quis minima minima quisquam quod velit soluta.",
                            Logo = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/843.jpg",
                            Name = "Klocko Group"
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CommodityEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityEntityId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e78a24c-09f0-aacc-56d2-757b45601894"),
                            CommodityEntityId = new Guid("badfe16c-bb87-d5a3-38e5-61bb4c04a5db"),
                            Description = "Magni maiores aperiam molestias ipsam. Harum reprehenderit nam libero reprehenderit maxime ut quisquam. Non voluptatum eius.",
                            Stars = 4,
                            Title = "Quisquam quis iure enim quidem libero."
                        },
                        new
                        {
                            Id = new Guid("04eaeae3-d2fa-bbff-a91e-85395a42ebc2"),
                            CommodityEntityId = new Guid("badfe16c-bb87-d5a3-38e5-61bb4c04a5db"),
                            Description = "Debitis error quod esse totam. Tempore perspiciatis numquam. Harum placeat architecto ipsa ducimus. Quia et nihil. Pariatur accusantium expedita enim natus in minima.",
                            Stars = 2,
                            Title = "Provident pariatur eum consequatur ex id rerum."
                        },
                        new
                        {
                            Id = new Guid("982e3e77-c57a-baf4-748e-652fc366b3c8"),
                            CommodityEntityId = new Guid("badfe16c-bb87-d5a3-38e5-61bb4c04a5db"),
                            Description = "Aut nam quod soluta qui vel perspiciatis. Odit officiis omnis soluta quia sint dolor sunt. Voluptas in et ducimus commodi laboriosam autem perferendis et consequatur. Quae veritatis occaecati et molestiae ut expedita aut ut consequatur.",
                            Stars = 1,
                            Title = "Accusantium ipsam voluptatibus."
                        },
                        new
                        {
                            Id = new Guid("a28e72ed-ff40-79ef-989a-a1ba11e37569"),
                            CommodityEntityId = new Guid("5dfa00c1-8d8f-1d17-4d3c-cc8f77ebca97"),
                            Description = "Reiciendis dolorem magnam iure et perferendis fuga. Voluptas mollitia repellat aspernatur consequuntur ex voluptas repudiandae odit. Est doloremque illum est aspernatur et magni. In eveniet laudantium.",
                            Stars = 5,
                            Title = "Illo pariatur ut et."
                        },
                        new
                        {
                            Id = new Guid("f8455396-a6d4-b3d0-e324-a82d63ea20ad"),
                            CommodityEntityId = new Guid("5dfa00c1-8d8f-1d17-4d3c-cc8f77ebca97"),
                            Description = "Explicabo non quas nostrum a ut ut. Et fuga corrupti. Commodi autem quo est rerum.",
                            Stars = 5,
                            Title = "Ea deleniti laudantium dignissimos perferendis."
                        },
                        new
                        {
                            Id = new Guid("303cf901-d5e2-768c-868d-3ebe66c17b05"),
                            CommodityEntityId = new Guid("5dfa00c1-8d8f-1d17-4d3c-cc8f77ebca97"),
                            Description = "Voluptatibus est optio. Iste soluta ipsam quos non quia velit. Voluptates voluptatem nam consequatur voluptas fugit dignissimos et dolor. Et commodi harum.",
                            Stars = 2,
                            Title = "Ad occaecati est eos inventore aut."
                        },
                        new
                        {
                            Id = new Guid("b2d5db21-0627-966f-4f4e-4c3be02f7bd8"),
                            CommodityEntityId = new Guid("e68f2ad4-5879-c913-0d34-f75b37b4b71b"),
                            Description = "Omnis fugiat eum harum vel. Est qui est ab esse voluptas odio explicabo. Distinctio quia aspernatur error. Autem cumque doloribus voluptatum soluta dicta amet nesciunt. Mollitia animi et eius expedita officiis labore.",
                            Stars = 3,
                            Title = "Nobis magni ullam nostrum."
                        },
                        new
                        {
                            Id = new Guid("7a6a07ab-5ab2-8c82-530a-453171d4d3e5"),
                            CommodityEntityId = new Guid("e68f2ad4-5879-c913-0d34-f75b37b4b71b"),
                            Description = "Rerum unde quidem ipsam quasi ullam. Quod ex corporis omnis ducimus odio veritatis facere. Quas voluptatem aut tenetur laudantium velit molestiae et. Laboriosam id in. Ut rerum et.",
                            Stars = 3,
                            Title = "Rerum omnis numquam occaecati ut iusto delectus reprehenderit eos."
                        },
                        new
                        {
                            Id = new Guid("f26ceb1c-7727-0204-f7a9-4eeccce40339"),
                            CommodityEntityId = new Guid("e68f2ad4-5879-c913-0d34-f75b37b4b71b"),
                            Description = "Rerum repudiandae qui iure eum sed aperiam. Dignissimos dignissimos dicta pariatur veritatis. Et suscipit accusamus aliquam placeat in sit. Voluptas minus omnis culpa.",
                            Stars = 3,
                            Title = "Quaerat eum magni dolores autem ullam odit impedit."
                        },
                        new
                        {
                            Id = new Guid("1f0bb658-dde4-db74-33b2-419e5ce20eaf"),
                            CommodityEntityId = new Guid("f1306022-13c3-8f5d-b27b-5a63d783839e"),
                            Description = "Quia sit veritatis soluta fuga neque libero ab nihil beatae. Soluta sunt velit. Natus illum consequatur ipsam iste ut voluptate vel et sit. Quo recusandae distinctio quisquam.",
                            Stars = 5,
                            Title = "Et aut ut et impedit officia enim."
                        },
                        new
                        {
                            Id = new Guid("e3050b5f-b607-c40e-560f-c0465a34ba9a"),
                            CommodityEntityId = new Guid("f1306022-13c3-8f5d-b27b-5a63d783839e"),
                            Description = "Consequatur dolorem quaerat qui maiores excepturi vero nemo iste. Nihil sed dolorem voluptate possimus reprehenderit. Quidem vel repudiandae beatae ut fugit aspernatur in. Labore enim voluptates odio ut temporibus.",
                            Stars = 3,
                            Title = "Iste hic sit harum maxime et expedita eveniet aperiam."
                        },
                        new
                        {
                            Id = new Guid("e77b1c0d-e7bb-7fb0-6028-f70fc6d7856d"),
                            CommodityEntityId = new Guid("f1306022-13c3-8f5d-b27b-5a63d783839e"),
                            Description = "Quo molestiae pariatur sit voluptatum beatae. Est rerum ut provident autem nostrum iusto optio aut. Blanditiis excepturi tempore velit nihil dolorem omnis vel sapiente. Vitae aut nobis aut dicta quis optio. Voluptates et qui.",
                            Stars = 3,
                            Title = "Est veniam distinctio ab minima maiores id."
                        });
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CommodityEntity", b =>
                {
                    b.HasOne("Shopster.DAL.Entities.CategoryEntity", "Category")
                        .WithMany("Commodities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopster.DAL.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("Commodities")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.RatingEntity", b =>
                {
                    b.HasOne("Shopster.DAL.Entities.CommodityEntity", "Commodity")
                        .WithMany("Ratings")
                        .HasForeignKey("CommodityEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Commodities");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.CommodityEntity", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Shopster.DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
